apiVersion: runwhen.com/v1
kind: GenerationRules
spec:
  platform: azure
  generationRules:
    - resourceTypes:
        - azure_compute_virtual_machines
      matchRules:
        - type: pattern
          pattern: ".+"
          properties: [name]
          mode: substring
      slxs:
        - baseName: az-vm-health
          qualifiers: ["resource_group"]
          baseTemplateName: azure-vm-health
          levelOfDetail: basic
          outputItems:
            - type: slx
            - type: sli
            - type: runbook
              templateName: azure-vm-health-taskset.yaml
            - type: workflow
