apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://placeholder.svg
  alias:  {{ match_resource.resource_group.name }} Azure Databricks Health
  asMeasuredBy: Composite health score of Databricks resources & activities. 
  configProvided:
  - name: SLX_PLACEHOLDER
    value: SLX_PLACEHOLDER
  owners:
  - {{workspace.owner_email}}
  statement: The health of Azure Databricks workspaces is measured by evaluating multiple factors like cluster health, job execution status, and resource utilization.
  additionalContext:
    name: "{{match_resource.resource.name}}"
    qualified_name: "{{ match_resource.qualified_name }}"
    resource_group: "{{ match_resource.resource_group.name }}"
    subscription_id: "{{ match_resource.subscription_id }}"
  tags:
    - name: cloud
      value: azure
    - name: service
      value: databricks
    - name: access
      value: read-only