apiVersion: runwhen.com/v1
kind: Workflow
metadata:
  name: {{slx_name}}-{{ "Azure Storage SLI Alert Workflow" | replace(" ", "-") | lower }}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  fromActivities:
  - displayName: {{resource_group.name}} Azure Storage SLI Alert Workflow
    description: Start RunSession with Eager Edgar when SLI is alerting for {{resource_group.name}} Azure Storage health
    actions:
    - tasks:
        slx: {{slx_name.split('--')[1]}}
        persona: eager-edgar
        titles:
          - '*'
        sessionTTL: 20m
    match:
      activityVerbs:
      - SLI_ALERTS_STARTED
      slxs:
      - {{slx_name.split('--')[1]}}
    name: {{resource_group.name}}-{{ "Azure Storage SLI Alert Workflow" | replace(" ", "-") | lower }}