apiVersion: runwhen.com/v1
kind: ServiceLevelIndicator
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  displayUnitsLong: OK
  displayUnitsShort: ok
  locations:
    - {{default_location}}
  description: Count Virtual machines that are publicly accessible, have high CPU usage, underutilized memory, stopped state, unused network interfaces, and unused public IPs in Azure
  codeBundle:
    {% if repo_url %}
    repoUrl: {{repo_url}}
    {% else %}
    repoUrl: https://github.com/runwhen-contrib/azure-c7n-codecollection.git
    {% endif %}
    {% if ref %}
    ref: {{ref}}
    {% else %}
    ref: main
    {% endif %}
    pathToRobot: codebundles/azure-vm-health/sli.robot
  intervalStrategy: intermezzo
  intervalSeconds: 600
  configProvided:
    - name: AZURE_RESOURCE_GROUP
      value: "{{resource_group.name}}"
    - name: AZURE_SUBSCRIPTION_NAME
      value: "{{ subscription_name }}"
    - name: AZURE_SUBSCRIPTION_ID
      value: "{{ subscription_id }}"
  secretsProvided:
  {% if wb_version %}
    {% include "azure-auth.yaml" ignore missing %}
  {% else %}
    - name: azure_credentials
      workspaceKey: AUTH DETAILS NOT FOUND
  {% endif %}

  alerts:
    warning:
      operator: <
      threshold: '1'
      for: '20m'
    ticket:
      operator: <
      threshold: '1'
      for: '40m'
    page:
      operator: '=='
      threshold: '0'
      for: ''